### ISSUE TITLE
error in writting cert.pem

### ISSUE THREAD

**Issue by klapvogn** [aeleos/cloudflared#17]
What am i doing wrong?

`klapvogn@PlexStreamer:~$ docker run -it --rm -v /home/klapvogn/docker/data/cloudflared:/home/nonroot/.cloudflared/ cloudflare/cloudflared:2021.9.1 tunnel login `

Please open the following URL and log in with your Cloudflare account:

https://dash.cloudflare.com/argotunnel?callback=https%3A%2F%2Flogin.cloudflareaccess.org%xxxxxxxxxxxxxxxxx%3D

Leave cloudflared running to download the cert automatically.
error writing cert to /home/nonroot/.cloudflared/cert.pem: open /home/nonroot/.cloudflared/cert.pem: permission denied

**Comment by aeleos** [comment]
That is strange, the only thing I can think of is to make sure that /home/klapvogn/docker/data/cloudflared has the right permissions to be written to by a docker container, for unraid its usually nobody:users

**Comment by sbh7600** [comment]
Hey!

Thanks for the reply, the only way i was able to create the .pem file was to give 777 perm to the folders. now i have it at 755 seems to work fine!
