### ISSUE TITLE
How to run two post args commands?

### ISSUE THREAD

**Issue by mitchross** [aeleos/cloudflared#19]
I want to run two commands,

 tunnel route dns 147de69d-xxxxxxaa3997169 xxxx.yyy.zzztunnel
 and
 run 147de69d-a46axxxxx3997169
 
How do I do this in the Unraid template?

Thanks

**Comment by aeleos** [comment]
The route command only exists to create a DNS record for you. This only happens once, so you shouldn't need it as a post arg. If you are looking to dynamically create the DNS records, I am not sure that putting it in post args is the right solution. Refer to this article for more detail. https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/routing-to-tunnel/dns
