### ISSUE TITLE
Update needed from 2020.7.0 to 2021.5.9

### ISSUE THREAD

**Issue by mcd92** [aeleos/cloudflared#4]
Hello,

Thank you for making available in your github the xml and instructions to run the Cloudflare container on an Unraid instance. This tool seems to be the only way I will get to open some services to the internet, since my ISP blocked ports 80 and 443 on my router, so I can only forward the other ones.

I'm trying to get the cloudflared docker functioning on my Unraid server. After some struggling, I managed to get it running with the right URL and HOSTNAME. But after less than a minute it shuts down, claiming the need to update cloudflared service:

![image](https://user-images.githubusercontent.com/20120390/120741190-fb17a200-c4ca-11eb-972a-18a22264d571.png)

I will note another issue I believe I have found, but in another ticket so it can be addressed separately.

Thank you very much in advance!

**Comment by mcd92** [comment]
Actually, after restarting the docker, it is already updated.

Should be remember though, that everytime one makes a change to the XML and rebuild the container, one needs to start it twice so it updates and then start with the updated version.

Perhaps it is actually an issue on the Cloudflare container, and cannot be address through the XML. Anyway, I believe this deserves a note on the instructions.

**Comment by aeleos** [comment]
This is a known issue, the best way around it is to add --restart unless-stopped to the extra paramters. Occasionally cloudflared will exit (unrelated to the update) when started and it always runs on the second start. Using --restart unless-stopped will cause the container to get restarted if cloudflared exits. Let me know if this fixes when you change the XML as it should

**Comment by aeleos** [comment]
Also, the template on CA is updated to include --restart unless-stopped by default, so hopefully this shouldn't warrant a note in the instructions

**Comment by mcd92** [comment]
Indeed, the --restart parameter is included in the XML. Also, I have tested the container for the last days and it is running smoothly.
Thanks!

**Comment by aeleos** [comment]
Great, glad I could help
