### ISSUE TITLE
Subdomains are not working for me

### ISSUE THREAD

**Issue by jsaltzman** [aeleos/cloudflared#9]
I have this working for http://mydomain.com but my subdomains are not working. I setup a cname record for the subdomain and I am pointing it at @. Any idea how I can fix this error?

Instead of pointing to @, I tried pointing at my tunnel (UUID.cdargotunnel.com) but that didn't work.

Subdomains were previously working. I am using nginx proxy manager.

**Comment by aeleos** [comment]
Can you post what error it shows when the subdomain isn't working, both from the browser and the cloudflared logs

**Comment by jsaltzman** [comment]
I flushed my DNS cache on my laptop and this resolved my problem. Thanks for the quick response.
